"use strict";/*
Monthly 2.2.2 by Kevin Thornbloom is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
*/(function(a){"use strict";a.fn.extend({monthly:function D(b){// How many days are in this month?
function c(a,b){return 2===a?3&b||!(b%25)&&15&b?28:29:30+(1&a+(a>>3))}// Build the month
function d(b,d){a(r).data("setMonth",b).data("setYear",d);// Get number of days
var e=0,g=c(b,d),// Get day of the week the first day is
i=b-1,k=new Date(d,i,1,0,0,0,0).getDay(),l=b===t&&d===u;// Remove old days
a(r+" .monthly-day, "+r+" .monthly-day-blank").remove(),a(r+" .monthly-event-list, "+r+" .monthly-day-wrap").empty();// Print out the days
for(var m=1;m<=g;m++){// Check if it's a day in the past
var n=p.stylePast&&(d<u||d===u&&(b<t||b===t&&m<v)),o="<div class=\"monthly-day-number\">"+m+"</div><div class=\"monthly-indicator-wrap\"></div>";if("event"===p.mode){var s=new Date(d,i,m,0,0,0,0);a(r+" .monthly-day-wrap").append("<div"+h("class","m-d monthly-day monthly-day-event"+(n?" monthly-past-day":"")+" dt"+s.toISOString().slice(0,10))+h("data-number",m)+">"+o+"</div>"),a(r+" .monthly-event-list").append("<div"+h("class","monthly-list-item")+h("id",q+"day"+m)+h("data-number",m)+"><div class=\"monthly-event-list-date\">"+A[s.getDay()]+"<br>"+m+"</div></div>")}else a(r+" .monthly-day-wrap").append("<a"+h("href","#")+h("class","m-d monthly-day monthly-day-pick"+(n?" monthly-past-day":""))+h("data-number",m)+">"+o+"</a>")}l&&a(r+" *[data-number=\""+v+"\"]").addClass("monthly-today"),a(r+" .monthly-header-title").html("<a href=\"#\" class=\"monthly-header-title-date\" onclick=\"return false\">"+z[b-1]+" "+d+"</a>"+(l&&a(r+" .monthly-event-list").hide()?"":"<a href=\"#\" class=\"monthly-reset\"></a>")),B?0===k?j(6):1!==k&&j(k-1):7!==k&&j(k);// Account for empty days at end
var w=a(r+" .monthly-day").length,x=a(r+" .monthly-day-blank").length,y=w+x,C=7*Math.ceil(y/7);if(0!=y%7)for(e=0;e<C-y;e++)a(r+" .monthly-day-wrap").append("<div class=\"m-d monthly-day-blank\"><div class=\"monthly-day-number\"></div></div>");// Events
"event"===p.mode&&f(b,d);var D=a(r+" .m-d");for(e=0;e<D.length;e+=7)D.slice(e,e+7).wrapAll("<div class=\"monthly-week\"></div>")}function e(b,d,e){// Year [0]   Month [1]   Day [2]
var f=k(b,"startdate"),g=k(b,"enddate"),i=f.split("-"),j=parseInt(i[0],10),m=parseInt(i[1],10),n=parseInt(i[2],10),o=n,q=n,s=n,t=m===d&&j===e,u=t;if(g){// If event has an end date, determine if the range overlaps this month
var v=g.split("-"),w=parseInt(v[0],10),x=parseInt(v[1],10),y=parseInt(v[2],10),z=x===d&&w===e;(t||z||(j<e||m<d&&j===e)&&(w>e||x>d&&w===e))&&(u=!0,o=t?n:1,q=z?y:c(d,e),s=t?o:1)}if(u){var A=k(b,"starttime"),B="",C=k(b,"url"),D=k(b,"name"),E=k(b,"class"),F=k(b,"color"),G=k(b,"id"),H=E?" "+E:"",I="<div",J="</span></div>";if(A){var K=k(b,"endtime");B="<div><div class=\"monthly-list-time-start\">"+l(A)+"</div>"+(K?"<div class=\"monthly-list-time-end\">"+l(K)+"</div>":"")+"</div>"}p.linkCalendarToEventUrl&&C&&(I="<a"+h("href",C),J="</span></a>");for(var L,M=I+h("data-eventid",G)+h("title",D)// BG and FG colors must match for left box shadow to create seamless link between dates
+(F?h("style","background:"+F+";color:"+F):""),N="<a"+h("href",C)+h("class","listed-event"+H)+h("data-eventid",G)+(F?h("style","background:"+F):"")+h("title",D)+">"+D+" "+B+"</a>",O=o;O<=q;O++)// Add to calendar view
// Add to event list
L=O===s,a(r+" *[data-number=\""+O+"\"] .monthly-indicator-wrap").append(M+h("class","monthly-event-indicator"+H// Include a class marking if this event continues from the previous day
+(L?"":" monthly-event-continued"))+"><span>"+(L?D:"")+J),a(r+" .monthly-list-item[data-number=\""+O+"\"]").addClass("item-has-event").append(N)}}function f(b,c){if(p.events)// Prefer local events if provided
g(p.events,b,c);else{var d="xml"===p.dataType?p.xmlUrl:p.jsonUrl;if(d){// Replace variables for month and year to load from dynamic sources
var e=(d+"").replace("{month}",b).replace("{year}",c);a.get(e,{now:a.now()},function(a){g(a,b,c)},p.dataType).fail(function(){console.error("Monthly.js failed to import "+d+". Please check for the correct path and "+p.dataType+" syntax.")})}}}function g(b,c,d){"xml"===p.dataType?a(b).find("event").each(function(a,b){e(b,c,d)}):"json"===p.dataType&&a.each(b.monthly,function(a,b){e(b,c,d)})}function h(a,b){for(var c=b+"",d="",e=0;e<c.length;e++)switch(c[e]){case"'":d+="&#39;";break;case"\"":d+="&quot;";break;case"<":d+="&lt;";break;case">":d+="&gt;";break;default:d+=c[e];}return" "+a+"=\""+d+"\""}// Detect the user's preferred language
// Use the user's locale if possible to obtain a list of short month names, falling back on English
function i(a,b,c){return p.useIsoDateFormat?new Date(a,b-1,c,0,0,0).toISOString().substring(0,10):"undefined"==typeof Intl?b+"/"+c+"/"+a:new Intl.DateTimeFormat(w).format(new Date(a,b-1,c,0,0,0))}// Use the user's locale if possible to obtain a list of short weekday names, falling back on English
function j(b){var c=a(r+" .monthly-day-wrap"),d=0;for(d=0;d<b;d++)c.prepend("<div class=\"m-d monthly-day-blank\"><div class=\"monthly-day-number\"></div></div>")}function k(b,c){return"xml"===p.dataType?a(b).find(c).text():b[c]}// Returns a 12-hour format hour/minute with period. Opportunity for future localization.
function l(a){var b=a.split(":"),c=parseInt(b[0],10),d="AM";return 12<c?(c-=12,d="PM"):12==c?d="PM":0==c&&(c=12),c+":"+(b[1]+" ")+d}function m(){var b=a(r).data("setMonth"),c=a(r).data("setYear"),e=12===b?1:b+1,f=12===b?c+1:c;d(e,f),o()}function n(){var b=a(r).data("setMonth"),c=a(r).data("setYear"),e=1===b?12:b-1,f=1===b?c-1:c;d(e,f),o()}// Function to go back to the month view
function o(){a(r+" .monthly-event-list").is(":visible")&&(a(r+" .monthly-cal").remove(),a(r+" .monthly-header-title").prepend("<a href=\"#\" class=\"monthly-cal\"></a>"))}// Advance months
// These are overridden by options declared in footer
var p=a.extend({dataType:"xml",disablePast:!1,eventList:!0,events:"",jsonUrl:"",linkCalendarToEventUrl:!1,maxWidth:!1,mode:"event",setWidth:!1,showTrigger:"",startHidden:!1,stylePast:!1,target:"",useIsoDateFormat:!1,weekStart:0,// Sunday
xmlUrl:""},b),q=a(this).attr("id"),r="#"+q,s=new Date,t=s.getMonth()+1,u=s.getFullYear(),v=s.getDate(),w=(p.locale||function(){return navigator.languages&&navigator.languages.length?navigator.languages[0]:navigator.language||navigator.browserLanguage}()).toLowerCase(),x=p.monthNameFormat||"short",y=p.weekdayNameFormat||"short",z=p.monthNames||function(){if("undefined"==typeof Intl)return["Jan","Feb","Mar","Apr","May","June","Jul","Aug","Sep","Oct","Nov","Dec"];for(var a,b=new Intl.DateTimeFormat(w,{month:x}),c=[],d=0;12>d;d++)a=new Date(2017,d,1,0,0,0),c[d]=b.format(a);return c}(),A=p.dayNames||function(){if("undefined"==typeof Intl)return["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];var a=new Intl.DateTimeFormat(w,{weekday:y}),b=[],c=0,d=null;for(c=0;7>c;c++)// 2017 starts on a Sunday, so use it to capture the locale's weekday names
d=new Date(2017,0,c+1,0,0,0),b[c]=a.format(d);return b}(),B="Mon"===p.weekStart||1===p.weekStart||"1"===p.weekStart,C=w.substring(0,2).toLowerCase();// Add Day Of Week Titles
// Add CSS classes for the primary language and the locale. This allows for CSS-driven
// overrides of the language-specific header buttons. Lowercased because locale codes
// are case-insensitive but CSS is not.
// Add Header & event list markup
// Set the calendar the first time
// Go back in months
// Reset Month
// Back to month view
// Click A Day
// Clicking an event within the list
!1!==p.maxWidth&&a(r).css("maxWidth",p.maxWidth),!1!==p.setWidth&&a(r).css("width",p.setWidth),p.startHidden&&(a(r).addClass("monthly-pop").css({display:"none",position:"absolute"}),a(document).on("focus",p.showTrigger+"",function(b){a(r).show(),b.preventDefault()}),a(document).on("click",p.showTrigger+""+", .monthly-pop",function(a){a.stopPropagation(),a.preventDefault()}),a(document).on("click",function(){a(r).hide()})),function(b){var c=b?1:0,d="",e=0;for(e=0;6>e;e++)d+="<div>"+A[e+c]+"</div>";d+="<div>"+A[b?0:6]+"</div>",a(r).append("<div class=\"monthly-day-title-wrap\">"+d+"</div><div class=\"monthly-day-wrap\"></div>")}(B),a(r).addClass("monthly-locale-"+C+" monthly-locale-"+w),a(r).prepend("<div class=\"monthly-header\"><div class=\"monthly-header-title\"><a href=\"#\" class=\"monthly-header-title-date\" onclick=\"return false\"></a></div><a href=\"#\" class=\"monthly-prev\"></a><a href=\"#\" class=\"monthly-next\"></a></div>").append("<div class=\"monthly-event-list\"></div>"),d(t,u),a(document.body).on("click",r+" .monthly-next",function(a){m(),a.preventDefault()}),a(document.body).on("click",r+" .monthly-prev",function(a){n(),a.preventDefault()}),a(document.body).on("click",r+" .monthly-reset",function(b){a(this).remove(),d(t,u),o(),b.preventDefault(),b.stopPropagation()}),a(document.body).on("click",r+" .monthly-cal",function(b){a(this).remove(),a(r+" .monthly-event-list").css("transform","scale(0)"),setTimeout(function(){a(r+" .monthly-event-list").hide()},250),b.preventDefault()}),a(document.body).on("click touchstart",r+" .monthly-day",function(b){// If events, show events list
var c=a(this).data("number");if("event"===p.mode&&p.eventList){var d=a(r+" .monthly-event-list"),e=document.getElementById(q+"day"+c),f=e.offsetTop;d.show(),d.css("transform"),d.css("transform","scale(1)"),a(r+" .monthly-list-item[data-number=\""+c+"\"]").show(),d.scrollTop(f),o(),p.linkCalendarToEventUrl||b.preventDefault()}else if("picker"===p.mode){var g=a(r).data("setMonth"),h=a(r).data("setYear");// Should days in the past be disabled?
a(this).hasClass("monthly-past-day")&&p.disablePast?b.preventDefault():(a(p.target+"").val(i(h,g,c)),p.startHidden&&a(r).hide()),b.preventDefault()}}),a(document.body).on("click",r+" .listed-event",function(b){var c=a(this).attr("href");// If there isn't a link, don't go anywhere
c||b.preventDefault()})}})})(jQuery);